#!/bin/sh
set -e

cat > ci/vars <<-EOF
# The version of openssl that we get from https://testssl.sh
export TARBALL="openssl-1.0.2k-chacha.pm.ipv6.Linux+FreeBSD.201705.tar.gz"

# Branches from https://github.com/drwetter/testssl.sh
export STABLE_BRANCH=2.8
export DEV_BRANCH=2.9dev

# You probably do not need to touch these.
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export CI_BUILD_URL=${CIRCLE_BUILD_URL}
export VCS_REF=$(git rev-parse --short HEAD)
export STABLE_TAG=\${STABLE_BRANCH}-\${BUILD_DATE}-git-\${VCS_REF}
export DEV_TAG=\${DEV_BRANCH}-\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars

docker-compose build
