#!/bin/sh
set -e

cat > ci/vars <<-EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars

echo '====> Build base image.'
docker build -t testssl:base -f src/Dockerfile-base src/

echo '====> Build image from branch "2.8".'
docker build -t testssl:2.8 --build-arg BRANCH=2.8 -f src/Dockerfile src/

echo '====> Build image from branch "2.9dev".'
docker build -t testssl:2.9dev --build-arg BRANCH=2.9dev -f src/Dockerfile src/
