#!/bin/bash
# vim: set sw=2 ts=2 ai et:
set -e
set -u
set -o pipefail

################################################################################
# Publish the image(s) to Docker Hub.
################################################################################

. ci/helpers.sh

. ci/vars

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}" quay.io

# Tag and push dev image.
docker tag testssl:"${DEV_BRANCH}" quay.io/jumanjiman/testssl:"${DEV_TAG}"
docker push quay.io/jumanjiman/testssl:"${DEV_TAG}"

# Tag and push stable image.
docker tag testssl:"${STABLE_BRANCH}" quay.io/jumanjiman/testssl:"${STABLE_TAG}"
docker push quay.io/jumanjiman/testssl:"${STABLE_TAG}"

# Tag and push stable image as "latest".
docker tag testssl:"${STABLE_BRANCH}" quay.io/jumanjiman/testssl:latest
docker push quay.io/jumanjiman/testssl:latest

docker logout quay.io
