#!/bin/sh
set -e
set -u

. ci/helpers.sh

. ci/vars

echo
echo '====> Check for things like trailing whitespace.'
ci/check-files

echo
echo '====> Test that images have correct versions.'
docker-compose -f docker-compose.ci.yaml run stable --version | grep "^[[:space:]]*testssl.sh.*${STABLE_BRANCH}"
docker-compose -f docker-compose.ci.yaml run dev    --version | grep "^[[:space:]]*testssl.sh.*${DEV_BRANCH}"

echo
echo '====> Test SSL of a website.'
docker-compose -f docker-compose.ci.yaml run stable --heartbleed --ip one https://www.google.com/
docker-compose -f docker-compose.ci.yaml run dev    --heartbleed --ip one https://www.google.com/

echo
echo '====> Check labels.'
if [ -n "${CIRCLECI:-}" ]; then
  docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.ci-build-url" }}' \
    testssl:${STABLE_BRANCH} | grep circleci.com
  docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.ci-build-url" }}' \
    testssl:${DEV_BRANCH} | grep circleci.com
fi
