#!/bin/bash
set -e
set -u

. ci/helpers.sh

. ci/vars

echo
echo '====> Check for things like trailing whitespace.'
ci/check-files -d

echo
echo '====> Test that images have correct versions.'
docker-compose -f docker-compose.ci.yaml run stable --version | grep "^[[:space:]]*testssl.sh.*${STABLE_BRANCH}"
docker-compose -f docker-compose.ci.yaml run dev    --version | grep "^[[:space:]]*testssl.sh.*${DEV_BRANCH}"

echo
echo '====> Test SSL of a website.'
docker-compose -f docker-compose.ci.yaml run stable --heartbleed --ip one https://www.google.com/
docker-compose -f docker-compose.ci.yaml run dev    --heartbleed --ip one https://www.google.com/

echo
echo '====> Check labels.'
# Ensure each image has labels.
docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.vcs-ref" }}' \
    testssl:"${STABLE_BRANCH}" | grep "${VCS_REF}"
docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.vcs-ref" }}' \
    testssl:"${DEV_BRANCH}" | grep "${VCS_REF}"

# We only apply this label for hands-free builds in CI.
if is_ci; then
  docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.ci-build-url" }}' \
    testssl:"${STABLE_BRANCH}" | grep circleci.com
  docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.ci-build-url" }}' \
    testssl:"${DEV_BRANCH}" | grep circleci.com
fi

echo
echo
