#!/bin/sh
set -e

. ci/vars

run_opts="
-i
-t
--rm
--read-only
--cap-drop     all
--memory       100M
--pids-limit   1000
--cpu-shares   512
"

echo '====> Test that images have correct versions.'
docker run ${run_opts} testssl:${STABLE_BRANCH} --version | grep "^[[:space:]]*testssl.sh.*${STABLE_BRANCH}"
docker run ${run_opts} testssl:${DEV_BRANCH}    --version | grep "^[[:space:]]*testssl.sh.*${DEV_BRANCH}"

echo '====> Test SSL of a website.'
docker run ${run_opts} testssl:${STABLE_BRANCH} --heartbleed --ip one https://www.google.com/
docker run ${run_opts} testssl:${DEV_BRANCH}    --heartbleed --ip one https://www.google.com/

echo '====> Check labels.'
if [ -n "${CIRCLECI}" ]; then
  docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.ci-build-url" }}' \
    testssl:${STABLE_BRANCH} | grep circleci.com
  docker inspect \
    -f '{{ index .Config.Labels "io.github.jumanjiman.ci-build-url" }}' \
    testssl:${DEV_BRANCH} | grep circleci.com
fi
