FROM alpine:3.5

ENV TARBALL="https://testssl.sh/openssl-1.0.2k-chacha.pm.ipv6.Linux+FreeBSD.tar.gz"

RUN apk --update-cache upgrade && \
    apk add \
      bash \
      bind-tools \
      coreutils \
      curl \
      ncurses \
      tzdata \
      && \
    rm -f /var/cache/apk/*

# Use the statically-compiled version of openssl from
# https://testssl.sh/
RUN cd /tmp/ && \
    curl -L -O https://testssl.sh/${TARBALL} && \
    tar xvzf ${TARBALL} && \
    cp -f bin/openssl.Linux.x86_64 /usr/bin/openssl && \
    rm -f ${TARBALL} && \
    rm -fr bin/

# Install RFC mapping file.
RUN curl -L -o /etc/mapping-rfc.txt https://testssl.sh/mapping-rfc.txt

ENTRYPOINT ["/testssl.sh"]
CMD ["-h"]
